name: insidelab
description: Real insights into graduate research labs
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Routing
  go_router: ^14.2.7
  flutter_web_plugins:
    sdk: flutter

  # Networking
  http: ^1.1.0
  dio: ^5.4.0

  # Data & Storage
  shared_preferences: ^2.2.2

  # Authentication
  google_sign_in: ^6.2.1

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2

  # Image Handling
  cached_network_image: ^3.3.0

  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0
  flutter_typeahead: ^5.2.0

  # Charts & Visualization
  fl_chart: ^0.71.0  # 버전 다운그레이드
  # radar_chart: ^2.0.0  # 필요시 추가

  # Animation
  animate_do: ^4.2.0

  # Icons
  font_awesome_flutter: ^10.6.0

  # Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Google Fonts 패키지를 사용하므로 폰트 파일 불필요
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-ExtraBold.ttf
  #         weight: 800

  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/